package com.vanuston.medeil.util;

import com.itextpdf.text.BaseColor;
import java.io.FileOutputStream;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.vanuston.medeil.client.RegistryFactory;
import com.vanuston.medeil.implementation.PurchaseOrder;
import com.vanuston.medeil.model.PurchaseOrderModel;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;

public class PurchaseOrderPDF {

    static Logger log = Logger.getLogger(PurchaseOrderPDF.class, "PurchaseOrderPDF");
    DateUtils dutils = new DateUtils();

    public String pdfCreator(String path, String filName, String shopName, String addres, String contact_address, String purNo, String tablename) throws RemoteException, NotBoundException {
        PurchaseOrder purchaseOrderController = (PurchaseOrder)RegistryFactory.getClientStub(RegistryConstants.PurchaseOrder);
        String htmlString = "<html><head><title></title></head><body bgcolor='white'><p><br></p><table align='center' bgcolor='lightyellow' border='1' width='1000px'>";
        try {
            String distname = "";
            String saddress = "";
            String tod = "";
            String pur_order_date = "";
            String con1 = "";            
            List<String> purcPDFDetail = purchaseOrderController.getPurcOrderDetailPDF(tablename, purNo);
            distname = purcPDFDetail.get(0).toString();
            saddress = purcPDFDetail.get(1).toString();
            tod = purcPDFDetail.get(2).toString();
            con1 = purcPDFDetail.get(3).toString();
            pur_order_date = dutils.normalFormatDate(purcPDFDetail.get(4).toString());

            Document document = new Document(PageSize.A4, 0, 0, 160, 180);
            document.addCreationDate();
            document.addProducer();
            String tit = shopName.concat("  -  ").concat(tablename);
            document.addTitle(tit);
            document.setMargins(10, 10, 80, 25);
            String pa = path.concat("\\pdf\\").concat(filName);
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(pa));
            document.open();
            PdfPTable table = new PdfPTable(1);
            table.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfContentByte cb = writer.getDirectContent();
            cb.setColorFill(BaseColor.BLACK);
            htmlString = htmlString.concat("<tr bgcolor='blue'><td align='center'><b><font color='white' size='20px'>Purchase Order</font></b> </td> </tr><tr><td align='center'><font size='7px'><b>");
            Paragraph purchaseOrder = new Paragraph("Purchase Order", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 18));
            Paragraph shopName1 = new Paragraph(shopName, FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 16));
            Paragraph dist_address1 = new Paragraph(addres, FontFactory.getFont(BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 8));
            Paragraph contacts = new Paragraph(contact_address, FontFactory.getFont(BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 8));
            Paragraph contacts1 = new Paragraph("", FontFactory.getFont(BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            purchaseOrder.setAlignment(Element.ALIGN_CENTER);
            shopName1.setAlignment(Element.ALIGN_CENTER);
            dist_address1.setAlignment(Element.ALIGN_CENTER);
            contacts.setAlignment(Element.ALIGN_CENTER);
            PdfPCell header = new PdfPCell();
            header.addElement(purchaseOrder);
            header.setBackgroundColor(BaseColor.CYAN);
            PdfPCell header1 = new PdfPCell();
            header1.addElement(shopName1);
            header1.addElement(dist_address1);
            header1.addElement(contacts);
            header1.addElement(contacts1);
            table.addCell(header);
            table.addCell(header1);
            PdfPTable table1 = new PdfPTable(2);
            table1.setHorizontalAlignment(Element.ALIGN_CENTER);
            String sh = " Order No : ".concat(purNo).concat("\n").concat(" Order Date : ").concat(pur_order_date);
            String sh1 = " Delivery  Date : ".concat("").concat("\n");
            Paragraph OrderDe = new Paragraph(sh, FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph OrderDe1 = new Paragraph(sh1, FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            OrderDe.setAlignment(Element.ALIGN_LEFT);
            OrderDe1.setAlignment(Element.ALIGN_LEFT);
            table1.addCell(OrderDe);
            table1.addCell(OrderDe1);
            PdfPTable table2 = new PdfPTable(2);
            table2.setHorizontalAlignment(Element.ALIGN_CENTER);
            String dist_name = " To : ".concat(distname).concat("\n").concat("      ").concat(saddress).concat("\n");
            String Dist_address = " Ship To : ".concat("\n").concat("   ").concat("").concat("\n").concat("  ").concat(" ");
            Paragraph dist_name1 = new Paragraph(dist_name, FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph Dist_address1 = new Paragraph(Dist_address, FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            dist_name1.setAlignment(Element.ALIGN_LEFT);
            Dist_address1.setAlignment(Element.ALIGN_LEFT);
            table2.addCell(dist_name1);
            table2.addCell(Dist_address1);
            PdfPTable table3 = new PdfPTable(1);
            String sde1 = " Delivery  Mode : ".concat(tod).concat("\n");
            Paragraph del = new Paragraph(sde1, FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            del.setAlignment(Element.ALIGN_LEFT);
            table3.addCell(del);
            PdfPTable table4 = new PdfPTable(15);
            PdfPCell tabl1 = new PdfPCell();
            PdfPCell tabl2 = new PdfPCell();
            PdfPCell tabl3 = new PdfPCell();
            PdfPCell tabl4 = new PdfPCell();
            PdfPCell tabl5 = new PdfPCell();
            PdfPCell tabl6 = new PdfPCell();
            PdfPCell tabl7 = new PdfPCell();
            Paragraph s_no = new Paragraph("S.No\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph ProduName = new Paragraph("Product Name\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph cname = new Paragraph("Company Name\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph qty = new Paragraph("Qty\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph up = new Paragraph("Unit Price\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph tax = new Paragraph("Tax\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph tot_amt = new Paragraph("Total Amt\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            s_no.setAlignment(Element.ALIGN_CENTER);
            tabl1.addElement(s_no);
            tabl1.setBackgroundColor(BaseColor.CYAN);
            ProduName.setAlignment(Element.ALIGN_CENTER);
            tabl2.addElement(ProduName);
            tabl2.setBackgroundColor(BaseColor.CYAN);
            tabl2.setColspan(4);
            cname.setAlignment(Element.ALIGN_CENTER);
            tabl3.addElement(cname);
            tabl3.setBackgroundColor(BaseColor.CYAN);
            tabl3.setColspan(4);
            qty.setAlignment(Element.ALIGN_CENTER);
            tabl4.addElement(qty);
            tabl4.setBackgroundColor(BaseColor.CYAN);
            up.setAlignment(Element.ALIGN_CENTER);
            tabl5.addElement(up);
            tabl5.setBackgroundColor(BaseColor.CYAN);
            tabl5.setColspan(2);
            tax.setAlignment(Element.ALIGN_CENTER);
            tabl6.addElement(tax);
            tabl6.setBackgroundColor(BaseColor.CYAN);
            tot_amt.setAlignment(Element.ALIGN_CENTER);
            tabl7.addElement(tot_amt);
            tabl7.setBackgroundColor(BaseColor.CYAN);
            tabl7.setColspan(2);
            table4.addCell(tabl1);
            table4.addCell(tabl2);
            table4.addCell(tabl3);
            table4.addCell(tabl4);
            table4.addCell(tabl5);
            table4.addCell(tabl6);
            table4.addCell(tabl7);
            htmlString = htmlString.concat(shopName);
            htmlString = htmlString.concat("</b></font><br><b><font size='4px'>");
            htmlString = htmlString.concat(addres).concat("</font></b><br> <b><font size='4px'>").concat(contact_address);
            htmlString = htmlString.concat("</font></b> <br></td></tr><tr><td align='left'><table width='100%' border='1' cellpadding='0' cellspacing='0'><tr> <td align='left' width='50%'><font size='4px'><b>");
            htmlString = htmlString.concat("</font></b> <br></td></tr><tr><td align='left'><table width='100%' border='1' cellpadding='0' cellspacing='0'><tr><td align='left' width='50%'><font size='4px'><b>Order No&nbsp;&nbsp; : </b>");
            htmlString = htmlString.concat(purNo).concat("<br><b>Order Date : </b>").concat(pur_order_date);
            htmlString = htmlString.concat("</font></td><td><font size='4px' width='50%'><b>Delivery Date :</b></font> </td></tr><tr><td align='left' width='50%'><font size='4px'><b>To &nbsp;&nbsp; : </b><br><br> <br><br></font></td><td><font size='4px' width='50%'><b>Ship To :</b><br><br><br><br></font></td></tr><tr><td colspan='2'><font size='4px'><b>Delivery Mode : </b>&nbsp;");
            htmlString = htmlString.concat(tod);
            htmlString = htmlString.concat("</font></td></tr></table></td></tr><tr><td><table border='1' width='100%' align='center'><tr><td width='5%' align='center'><b><font size='4px'>S.No</font></b></td><td width='30%' align='center'><b><font size='4px'>Product Name</font></b></td><td width='28%' align='center'><b><font size='4px'>Company Name</font></b></td><td width='5%' align='center'><b><font size='4px'>Qty</font></b></td><td width='10%' align='center'><b><font size='4px'>UnitPrice</font></b></td><td width='10%' align='center'><b><font size='4px'>Tax</font></b></td><td width='12%' align='center'><b><font size='4px'>Total Amount</font> </b></td> </tr>");
            
            PurchaseOrderModel purcModel = new PurchaseOrderModel();
            Object purcDetails = purchaseOrderController.getPurcOrderTDetailPDF(tablename, purNo);
            purcModel = (PurchaseOrderModel) purcDetails;
            PurchaseOrderModel pModel;
            List<PurchaseOrderModel> purcOrderBill = new ArrayList<PurchaseOrderModel>();
            purcOrderBill = purcModel.getListofitems();
            int index = 0;
            for (index = 0; index < purcOrderBill.size(); index++) {
                pModel = purcOrderBill.get(index);
                tabl1 = new PdfPCell();
                tabl2 = new PdfPCell();
                tabl3 = new PdfPCell();
                tabl4 = new PdfPCell();
                tabl5 = new PdfPCell();
                tabl6 = new PdfPCell();
                tabl7 = new PdfPCell();
                String smno = String.valueOf(index + 1);
                String proName = pModel.getPurcOrderIN();
                String mfgName = pModel.getPurcOrderDos();
                String qt = String.valueOf(pModel.getPurcOrderQty());
                htmlString = htmlString.concat("<tr><td width='5%' align='center'>").concat(smno).concat("</td><td width='30%' align='center'>").concat(proName).concat(" </td><td width='25%' align='center'>").concat(mfgName).concat("</td><td width='5%' align='center'>").concat(qt).concat("</td><td width='10%' align='center'>&nbsp;</td><td width='10%' align='center'>&nbsp;</td><td width='12%' align='center'>&nbsp;</td> </tr>");
                Paragraph s_no1 = new Paragraph(smno + "\n", FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
                Paragraph ProduName1 = new Paragraph(proName + "\n", FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
                Paragraph cname1 = new Paragraph(mfgName + "\n", FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
                Paragraph qty1 = new Paragraph(qt + "\n", FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
                Paragraph up1 = new Paragraph("\n", FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
                Paragraph tax1 = new Paragraph("\n", FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
                Paragraph tot_amt1 = new Paragraph("\n", FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
                s_no1.setAlignment(Element.ALIGN_CENTER);
                tabl1.addElement(s_no1);
                ProduName1.setAlignment(Element.ALIGN_LEFT);
                tabl2.addElement(ProduName1);
                tabl2.setColspan(4);
                cname1.setAlignment(Element.ALIGN_LEFT);
                tabl3.addElement(cname1);
                tabl3.setColspan(4);
                qty1.setAlignment(Element.ALIGN_CENTER);
                tabl4.addElement(qty1);
                up1.setAlignment(Element.ALIGN_CENTER);
                tabl5.addElement(up1);
                tabl5.setColspan(2);
                tax1.setAlignment(Element.ALIGN_CENTER);
                tabl6.addElement(tax1);
                tot_amt1.setAlignment(Element.ALIGN_CENTER);
                tabl7.addElement(tot_amt1);
                tabl7.setColspan(2);
                table4.addCell(tabl1);
                table4.addCell(tabl2);
                table4.addCell(tabl3);
                table4.addCell(tabl4);
                table4.addCell(tabl5);
                table4.addCell(tabl6);
                table4.addCell(tabl7);
            }
            PdfPTable TotalTable = new PdfPTable(4);
            PdfPCell cellsig = new PdfPCell();
            PdfPCell cellsig1 = new PdfPCell();
            cellsig.setColspan(3);
            cellsig1.setColspan(4);
            PdfPTable subTable = new PdfPTable(2);
            PdfPCell cellSubTable = new PdfPCell();
            PdfPCell cellSubTable1 = new PdfPCell();
            PdfPCell celltax1 = new PdfPCell();
            PdfPCell celltax2 = new PdfPCell();
            PdfPCell celltotal = new PdfPCell();
            PdfPCell celltotal1 = new PdfPCell();
            PdfPCell cellShipping = new PdfPCell();
            PdfPCell cellShipping1 = new PdfPCell();
            PdfPCell cellGrandTotal = new PdfPCell();
            PdfPCell cellGrandTotal1 = new PdfPCell();
            Paragraph SubTotal = new Paragraph("Sub Total\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph SubTotal1 = new Paragraph("\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph tax1 = new Paragraph("Tax\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph tax2 = new Paragraph("\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph total = new Paragraph("Total\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph total1 = new Paragraph("\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph Shipping = new Paragraph("Shipping\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph Shipping2 = new Paragraph("\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph GrandTotal = new Paragraph("Grand Total\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph GrandTotal1 = new Paragraph("\n", FontFactory.getFont(BaseFont.HELVETICA_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 10));
            Paragraph asig = new Paragraph("Authorized Signature :  \n", FontFactory.getFont(BaseFont.COURIER_BOLD, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 9));
            SubTotal.setAlignment(Element.ALIGN_LEFT);
            tax1.setAlignment(Element.ALIGN_LEFT);
            total.setAlignment(Element.ALIGN_LEFT);
            Shipping.setAlignment(Element.ALIGN_LEFT);
            GrandTotal.setAlignment(Element.ALIGN_LEFT);
            asig.setAlignment(Element.ALIGN_LEFT);
            cellSubTable.addElement(SubTotal);
            cellSubTable1.addElement(SubTotal1);
            celltax1.addElement(tax1);
            celltax2.addElement(tax2);
            celltotal.addElement(total);
            celltotal1.addElement(total1);
            cellShipping.addElement(Shipping);
            cellShipping1.addElement(Shipping2);
            cellGrandTotal.addElement(GrandTotal);
            cellGrandTotal1.addElement(GrandTotal1);
            subTable.addCell(cellSubTable);
            subTable.addCell(cellSubTable1);
            subTable.addCell(celltax1);
            subTable.addCell(celltax2);
            subTable.addCell(celltotal);
            subTable.addCell(celltotal1);
            subTable.addCell(cellShipping);
            subTable.addCell(cellShipping1);
            subTable.addCell(cellGrandTotal);
            subTable.addCell(cellGrandTotal1);
            cellsig.addElement(asig);
            TotalTable.addCell(cellsig);
            TotalTable.addCell(subTable);
            PdfPTable unable = new PdfPTable(1);
            PdfPCell unableCell = new PdfPCell();
            Paragraph UNABLEcALL = new Paragraph("If you are unable to deliver by the date shown,please call  " + con1 + "\n", FontFactory.getFont(BaseFont.TIMES_ROMAN, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED, 8));
            UNABLEcALL.setAlignment(Element.ALIGN_LEFT);
            unableCell.addElement(UNABLEcALL);
            unableCell.setBackgroundColor(BaseColor.PINK);
            unable.addCell(unableCell);
            document.add(table);
            document.add(table1);
            document.add(table2);
            document.add(table3);
            document.add(table4);
            document.add(TotalTable);
            document.add(unable);
            document.close();
            htmlString = htmlString.concat(" <tr><td colspan='4' valign='top'><b><font color='blue' size='4px'>Authorized Signature : </font></b></td><td colspan='3' align='left'><table border='1' cellpadding='0' cellspacing='0' align='left' width='100%'> <tr><td width='58%'><font size='4px'><b>Sub Total</b></font> </td><td width='33%'>&nbsp;</td></tr><tr><td width='200'><font size='4px'><b>Tax</b></font> </td><td>&nbsp;</td></tr>");
            htmlString = htmlString.concat("<tr><td width='200'><font size='4px'><b>Total</b></font> </td><td>&nbsp;</td></tr><tr><td width='200'><font size='4px'><b>Shipping</b></font> </td><td>&nbsp;</td></tr><tr><td width='200'><font size='4px'><b>Grand Total</b></font> </td><td>&nbsp;</td></tr></table></td></tr>");
            htmlString = htmlString.concat("<tr><td colspan='7' bgcolor='pink'><b><font size='3px'>if you are unable to deliver by the date shown,please call  ");
            htmlString = htmlString.concat(con1);
            htmlString = htmlString.concat("</font> </b></td></tr></table></td></tr></table></body></html>");
        } catch (Exception e) {
            String msg = "   Class : PurchaseOrderPDF  Method : PurchaseOrderPDF Exception : " + e.getMessage();
            log.debug(msg);
        }
        return htmlString;
    }
}