/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DrugSpecifications.java
 *
 * Created on Jan 8, 2014, 6:13:27 PM
 */

package com.vanuston.medeil.uitables;

import com.vanuston.medeil.client.RegistryFactory;
import com.vanuston.medeil.implementation.CommonImplements;
import com.vanuston.medeil.implementation.Prescription;
import com.vanuston.medeil.model.DrugSpecificationModel;
import com.vanuston.medeil.util.Logger;
import com.vanuston.medeil.util.RegistryConstants;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.util.List;
import javafx.stage.Alert;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author muralikrishnan
 */
public class DrugSpecifications extends javax.swing.JDialog {
    static Logger log = Logger.getLogger(DrugSpecifications.class, "Uitables");
    CommonImplements commonController;
    JComboBox jc = new JComboBox();
    
    /** Creates new form DrugSpecifications */
    public DrugSpecifications() {
        initComponents();        
        setModal(true);        
        jc.addItemListener(new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent e) {
                   displayItemDetails();
                }
            });        

        InputMap im = jPanel1.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        im.put(KeyStroke.getKeyStroke(KeyEvent.VK_F7, 0),"update");
        im.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),"escape");
        ActionMap ac = jPanel1.getActionMap();
        ac.put("update", new AbstractAction("update") {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    updateDetails();
                }
            });


        ac.put("escape", new AbstractAction("escape") {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    dispose();
                }
            });
    }

   

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtGenericName = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        txtChemicalFormula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCategories = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtIndication = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPharmacoDynamics = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtMechanism = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtAbsorption = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtMetabolism = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtVolumeDistribution = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtRouteElimination = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtHalfLife = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtToxicity = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtFoodInteraction = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Drug Specifications");
        setResizable(false);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("GENERIC NAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 118, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CHEMICAL FORMULA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("DESCRIPTION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 102, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("CATEGORIES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 89, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("INDICATION");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 76, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("PHARMACODYNAMICS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 160, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("MECHANISM");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 101, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("ABSORPTION");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 760, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("VOLUME DISTRIBUTION");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1010, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("METABOLISM");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 880, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("ROUTE OF ELIMINATION");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1080, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("HALF LIFE");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("TOXICITY");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1270, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("FOOD INTERACTIONS");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtGenericName.setEditable(false);
        jPanel1.add(txtGenericName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 380, -1));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setAutoscrolls(true);

        txtDescription.setColumns(20);
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtDescription);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 693, -1));
        jPanel1.add(txtChemicalFormula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 380, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);

        txtCategories.setColumns(20);
        txtCategories.setLineWrap(true);
        txtCategories.setRows(5);
        txtCategories.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtCategories);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 693, 40));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setAutoscrolls(true);

        txtIndication.setColumns(20);
        txtIndication.setLineWrap(true);
        txtIndication.setRows(5);
        txtIndication.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtIndication);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 693, -1));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setAutoscrolls(true);

        txtPharmacoDynamics.setColumns(20);
        txtPharmacoDynamics.setLineWrap(true);
        txtPharmacoDynamics.setRows(5);
        txtPharmacoDynamics.setWrapStyleWord(true);
        jScrollPane5.setViewportView(txtPharmacoDynamics);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 693, -1));

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setAutoscrolls(true);

        txtMechanism.setColumns(20);
        txtMechanism.setLineWrap(true);
        txtMechanism.setRows(5);
        txtMechanism.setWrapStyleWord(true);
        jScrollPane6.setViewportView(txtMechanism);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, 693, -1));

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setAutoscrolls(true);

        txtAbsorption.setColumns(20);
        txtAbsorption.setLineWrap(true);
        txtAbsorption.setRows(5);
        txtAbsorption.setWrapStyleWord(true);
        jScrollPane7.setViewportView(txtAbsorption);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 760, 693, -1));

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setAutoscrolls(true);

        txtMetabolism.setColumns(20);
        txtMetabolism.setLineWrap(true);
        txtMetabolism.setRows(5);
        txtMetabolism.setWrapStyleWord(true);
        jScrollPane8.setViewportView(txtMetabolism);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 880, 693, -1));

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setAutoscrolls(true);

        txtVolumeDistribution.setColumns(20);
        txtVolumeDistribution.setLineWrap(true);
        txtVolumeDistribution.setRows(5);
        txtVolumeDistribution.setWrapStyleWord(true);
        jScrollPane9.setViewportView(txtVolumeDistribution);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1010, 693, 46));

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setAutoscrolls(true);

        txtRouteElimination.setColumns(20);
        txtRouteElimination.setLineWrap(true);
        txtRouteElimination.setRows(5);
        txtRouteElimination.setWrapStyleWord(true);
        jScrollPane10.setViewportView(txtRouteElimination);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1080, 693, -1));

        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setAutoscrolls(true);

        txtHalfLife.setColumns(20);
        txtHalfLife.setLineWrap(true);
        txtHalfLife.setRows(5);
        txtHalfLife.setWrapStyleWord(true);
        jScrollPane11.setViewportView(txtHalfLife);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1200, 693, 48));

        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setAutoscrolls(true);

        txtToxicity.setColumns(20);
        txtToxicity.setLineWrap(true);
        txtToxicity.setRows(5);
        txtToxicity.setWrapStyleWord(true);
        jScrollPane12.setViewportView(txtToxicity);

        jPanel1.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1270, 693, -1));

        jScrollPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane13.setAutoscrolls(true);

        txtFoodInteraction.setColumns(20);
        txtFoodInteraction.setLineWrap(true);
        txtFoodInteraction.setRows(5);
        txtFoodInteraction.setWrapStyleWord(true);
        jScrollPane13.setViewportView(txtFoodInteraction);

        jPanel1.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 128, 693, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("DRUG SPECIFICATIONS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 11, 234, -1));

        jScrollPane2.setViewportView(jPanel1);

        jButton1.setText("Update [F7]");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(377, 377, 377)
                        .add(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 527, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-982)/2, (screenSize.height-626)/2, 982, 626);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       updateDetails();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void updateDetails() {
         try {
            if(txtGenericName.getText().equals("")) {
                Alert.inform("Drug Specifications","The details cannot be updated since generic name is empty");
            }
            else {
                ConfirmDialogBox cd = new ConfirmDialogBox(0, "Drug Specifications");
                if(cd.staus==true) {
                    commonController = (CommonImplements) RegistryFactory.getClientStub(RegistryConstants.CommonImplements);
                    String genericName=commonController.getQueryValue("select generic_name from drug_specifications where generic_name='"+jc.getSelectedItem().toString()+"'");
                    Prescription prescriptionController = (Prescription) RegistryFactory.getClientStub(RegistryConstants.PrescriptionFormat);
                    DrugSpecificationModel drugSpecificationModel = new DrugSpecificationModel();
                    if(genericName.equals("")) {
                        drugSpecificationModel.setSaveType("save");
                    }
                    else {
                        drugSpecificationModel.setSaveType("update");
                    }
                    drugSpecificationModel.setGenericName(jc.getSelectedItem().toString());
                    drugSpecificationModel.setDescription(txtDescription.getText().trim());
                    drugSpecificationModel.setCategories(txtCategories.getText().trim());
                    drugSpecificationModel.setChemicalFormula(txtChemicalFormula.getText().trim());
                    drugSpecificationModel.setIndication(txtIndication.getText().trim());
                    drugSpecificationModel.setPharmaCodynamics(txtPharmacoDynamics.getText().trim());
                    drugSpecificationModel.setMechanism(txtMechanism.getText().trim());
                    drugSpecificationModel.setVolumeDistribution(txtVolumeDistribution.getText().trim());
                    drugSpecificationModel.setMetabolism(txtMetabolism.getText().trim());
                    drugSpecificationModel.setRouteElimination(txtRouteElimination.getText().trim());
                    drugSpecificationModel.setAbsorption(txtAbsorption.getText().trim());
                    drugSpecificationModel.setHalfLife(txtHalfLife.getText().trim());
                    drugSpecificationModel.setToxicity(txtToxicity.getText().trim());
                    drugSpecificationModel.setFoodInteractions(txtFoodInteraction.getText().trim());
                    int i=prescriptionController.insertDrugSpecification(drugSpecificationModel);
                    if(i > 0)
                    JOptionPane.showMessageDialog(rootPane, "Data saved successfully");
                }
            }
        } catch (Exception e) {
            String msg = "Class : DrugSpecifications  Method : displayItemDetails  = " + e.getMessage();
            log.debug(msg);
        }
    }

    public void displayItemDetails() {
    try {
         commonController = (CommonImplements) RegistryFactory.getClientStub(RegistryConstants.CommonImplements);
         List<String> drugSpecificationList=commonController.getQueryValue("SELECT  generic_name, description, categories, chemical_formula, ds.indication, Pharmacodynamics, mechanism, volume_distribution, metabolism, route_elimination, absorption, half_life, toxicity, food_interactions"
                + " FROM drug_specifications ds  where generic_name='"+jc.getSelectedItem().toString()+"' limit 1",14);
         if(!drugSpecificationList.isEmpty())  {
                txtDescription.setText(drugSpecificationList.get(1));
                txtCategories.setText(drugSpecificationList.get(2));
                txtChemicalFormula.setText(drugSpecificationList.get(3));
                txtIndication.setText(drugSpecificationList.get(4));
                txtPharmacoDynamics.setText(drugSpecificationList.get(5));
                txtMechanism.setText(drugSpecificationList.get(6));
                txtVolumeDistribution.setText(drugSpecificationList.get(7));
                txtMetabolism.setText(drugSpecificationList.get(8));
                txtRouteElimination.setText(drugSpecificationList.get(9));
                txtAbsorption.setText(drugSpecificationList.get(10));
                txtHalfLife.setText(drugSpecificationList.get(11));
                txtToxicity.setText(drugSpecificationList.get(12));
                txtFoodInteraction.setText(drugSpecificationList.get(13));
            }
            else {
                txtDescription.setText("");
                txtCategories.setText("");
                txtChemicalFormula.setText("");
                txtIndication.setText("");
                txtPharmacoDynamics.setText("");
                txtMechanism.setText("");
                txtVolumeDistribution.setText("");
                txtMetabolism.setText("");
                txtRouteElimination.setText("");
                txtAbsorption.setText("");
                txtHalfLife.setText("");
                txtToxicity.setText("");
                txtFoodInteraction.setText("");
            }
        }
    catch(Exception e) {
         String msg = "Class : DrugSpecifications  Method : displayItemDetails  = " + e.getMessage();
         log.debug(msg);
    }
    }    
    public void loadSpecifications(String itemName,String foodInteraction) {
        try {
            if(foodInteraction.equals("yes")) {
                removeComponents();
            }
            commonController = (CommonImplements) RegistryFactory.getClientStub(RegistryConstants.CommonImplements);
            String genericNames = commonController.getQueryValue("SELECT  genericname from drugtable where concat(itemname,'_',dosage,' |',formulation)='"+itemName+"' limit 1");
            String[] genericName= genericNames.split(",");            
            for(int i=0; i <genericName.length; i++) {
                jc.addItem(genericName[i]);
                jc.setPreferredSize(new Dimension(350, jc.getPreferredSize().height));
                jPanel1.add(jc,new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 118, -1));
            }            
            txtGenericName.setText(genericNames);
            displayItemDetails();
        }
        catch(Exception e) {
            String msg = "Class : DrugSpecifications  Method : loadSpecifications  = " + e.getMessage();
            log.debug(msg);
        }
    }

    private void removeComponents() {
        jPanel1.remove(jScrollPane1);
        jPanel1.remove(txtChemicalFormula);
        jPanel1.remove(jLabel2);
        jPanel1.remove(jLabel3);
        jPanel1.remove(jLabel4);
        jPanel1.remove(jScrollPane3);
        jPanel1.remove(jScrollPane4);
        jPanel1.remove(jLabel6);
        jPanel1.remove(jScrollPane5);
        jPanel1.remove(jLabel7);
        jPanel1.remove(jScrollPane6);
        jPanel1.remove(jLabel8);
        jPanel1.remove(jScrollPane7);
        jPanel1.remove(jLabel9);
        jPanel1.remove(jScrollPane8);
        jPanel1.remove(jLabel10);
        jPanel1.remove(jScrollPane9);
        jPanel1.remove(jLabel11);
        jPanel1.remove(jScrollPane10);
        jPanel1.remove(jLabel12);
        jPanel1.remove(jScrollPane11);
        jPanel1.remove(jLabel13);
        jPanel1.remove(jScrollPane12);
        jPanel1.remove(jLabel14);
        setPreferredSize(new Dimension(974,300));
        setLocation(300, 300);
        jPanel1.setPreferredSize(new Dimension(903,180));
        jLabel5.setText("FOOD INTERACTIONS");
        txtFoodInteraction.setEditable(false);
        jPanel1.revalidate();
        pack();
    }
    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea txtAbsorption;
    private javax.swing.JTextArea txtCategories;
    private javax.swing.JTextField txtChemicalFormula;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextArea txtFoodInteraction;
    private javax.swing.JTextField txtGenericName;
    private javax.swing.JTextArea txtHalfLife;
    private javax.swing.JTextArea txtIndication;
    private javax.swing.JTextArea txtMechanism;
    private javax.swing.JTextArea txtMetabolism;
    private javax.swing.JTextArea txtPharmacoDynamics;
    private javax.swing.JTextArea txtRouteElimination;
    private javax.swing.JTextArea txtToxicity;
    private javax.swing.JTextArea txtVolumeDistribution;
    // End of variables declaration//GEN-END:variables

}
